"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserFriendlyMessages = exports.ErrorCodeToStatusCode = exports.CategoryToSeverity = exports.ErrorSeverity = exports.ErrorCodeCategoryMap = exports.ErrorCategory = exports.ErrorCode = void 0;
exports.getUserFriendlyMessage = getUserFriendlyMessage;
exports.ErrorCode = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_REQUEST: "INVALID_REQUEST",
    INVALID_PARAMETER: "INVALID_PARAMETER",
    MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
    INVALID_FORMAT: "INVALID_FORMAT",
    AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
    CREDENTIALS_INVALID: "CREDENTIALS_INVALID",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
    ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
    MFA_REQUIRED: "MFA_REQUIRED",
    MFA_INVALID: "MFA_INVALID",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    FORBIDDEN: "FORBIDDEN",
    INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
    RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",
    NOT_FOUND: "NOT_FOUND",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    ENDPOINT_NOT_FOUND: "ENDPOINT_NOT_FOUND",
    CONFLICT: "CONFLICT",
    DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
    RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
    VERSION_CONFLICT: "VERSION_CONFLICT",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
    BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
    INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
    PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
    OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
    WORKFLOW_ERROR: "WORKFLOW_ERROR",
    EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
    THIRD_PARTY_API_ERROR: "THIRD_PARTY_API_ERROR",
    PAYMENT_GATEWAY_ERROR: "PAYMENT_GATEWAY_ERROR",
    EMAIL_SERVICE_ERROR: "EMAIL_SERVICE_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
    UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",
    FOREIGN_KEY_VIOLATION: "FOREIGN_KEY_VIOLATION",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    MAINTENANCE_MODE: "MAINTENANCE_MODE",
    FEATURE_NOT_IMPLEMENTED: "FEATURE_NOT_IMPLEMENTED",
    CIRCUIT_BREAKER_OPEN: "CIRCUIT_BREAKER_OPEN",
    CIRCUIT_BREAKER_HALF_OPEN: "CIRCUIT_BREAKER_HALF_OPEN",
};
var ErrorCategory;
(function (ErrorCategory) {
    ErrorCategory["VALIDATION"] = "VALIDATION";
    ErrorCategory["AUTHENTICATION"] = "AUTHENTICATION";
    ErrorCategory["AUTHORIZATION"] = "AUTHORIZATION";
    ErrorCategory["NOT_FOUND"] = "NOT_FOUND";
    ErrorCategory["CONFLICT"] = "CONFLICT";
    ErrorCategory["RATE_LIMIT"] = "RATE_LIMIT";
    ErrorCategory["BUSINESS_LOGIC"] = "BUSINESS_LOGIC";
    ErrorCategory["EXTERNAL_SERVICE"] = "EXTERNAL_SERVICE";
    ErrorCategory["DATABASE"] = "DATABASE";
    ErrorCategory["INTERNAL"] = "INTERNAL";
})(ErrorCategory || (exports.ErrorCategory = ErrorCategory = {}));
exports.ErrorCodeCategoryMap = {
    [exports.ErrorCode.VALIDATION_ERROR]: ErrorCategory.VALIDATION,
    [exports.ErrorCode.INVALID_REQUEST]: ErrorCategory.VALIDATION,
    [exports.ErrorCode.INVALID_PARAMETER]: ErrorCategory.VALIDATION,
    [exports.ErrorCode.MISSING_REQUIRED_FIELD]: ErrorCategory.VALIDATION,
    [exports.ErrorCode.INVALID_FORMAT]: ErrorCategory.VALIDATION,
    [exports.ErrorCode.AUTHENTICATION_FAILED]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.TOKEN_EXPIRED]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.TOKEN_INVALID]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.REFRESH_TOKEN_EXPIRED]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.CREDENTIALS_INVALID]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.ACCOUNT_LOCKED]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.ACCOUNT_DISABLED]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.MFA_REQUIRED]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.MFA_INVALID]: ErrorCategory.AUTHENTICATION,
    [exports.ErrorCode.PERMISSION_DENIED]: ErrorCategory.AUTHORIZATION,
    [exports.ErrorCode.FORBIDDEN]: ErrorCategory.AUTHORIZATION,
    [exports.ErrorCode.INSUFFICIENT_PERMISSIONS]: ErrorCategory.AUTHORIZATION,
    [exports.ErrorCode.RESOURCE_ACCESS_DENIED]: ErrorCategory.AUTHORIZATION,
    [exports.ErrorCode.NOT_FOUND]: ErrorCategory.NOT_FOUND,
    [exports.ErrorCode.USER_NOT_FOUND]: ErrorCategory.NOT_FOUND,
    [exports.ErrorCode.RESOURCE_NOT_FOUND]: ErrorCategory.NOT_FOUND,
    [exports.ErrorCode.ENDPOINT_NOT_FOUND]: ErrorCategory.NOT_FOUND,
    [exports.ErrorCode.CONFLICT]: ErrorCategory.CONFLICT,
    [exports.ErrorCode.DUPLICATE_ENTRY]: ErrorCategory.CONFLICT,
    [exports.ErrorCode.RESOURCE_ALREADY_EXISTS]: ErrorCategory.CONFLICT,
    [exports.ErrorCode.VERSION_CONFLICT]: ErrorCategory.CONFLICT,
    [exports.ErrorCode.RATE_LIMIT_EXCEEDED]: ErrorCategory.RATE_LIMIT,
    [exports.ErrorCode.QUOTA_EXCEEDED]: ErrorCategory.RATE_LIMIT,
    [exports.ErrorCode.BUSINESS_RULE_VIOLATION]: ErrorCategory.BUSINESS_LOGIC,
    [exports.ErrorCode.INSUFFICIENT_BALANCE]: ErrorCategory.BUSINESS_LOGIC,
    [exports.ErrorCode.PLAN_LIMIT_REACHED]: ErrorCategory.BUSINESS_LOGIC,
    [exports.ErrorCode.OPERATION_NOT_ALLOWED]: ErrorCategory.BUSINESS_LOGIC,
    [exports.ErrorCode.WORKFLOW_ERROR]: ErrorCategory.BUSINESS_LOGIC,
    [exports.ErrorCode.EXTERNAL_SERVICE_ERROR]: ErrorCategory.EXTERNAL_SERVICE,
    [exports.ErrorCode.THIRD_PARTY_API_ERROR]: ErrorCategory.EXTERNAL_SERVICE,
    [exports.ErrorCode.PAYMENT_GATEWAY_ERROR]: ErrorCategory.EXTERNAL_SERVICE,
    [exports.ErrorCode.EMAIL_SERVICE_ERROR]: ErrorCategory.EXTERNAL_SERVICE,
    [exports.ErrorCode.DATABASE_ERROR]: ErrorCategory.DATABASE,
    [exports.ErrorCode.RECORD_NOT_FOUND]: ErrorCategory.DATABASE,
    [exports.ErrorCode.UNIQUE_CONSTRAINT_VIOLATION]: ErrorCategory.DATABASE,
    [exports.ErrorCode.FOREIGN_KEY_VIOLATION]: ErrorCategory.DATABASE,
    [exports.ErrorCode.INTERNAL_ERROR]: ErrorCategory.INTERNAL,
    [exports.ErrorCode.SERVICE_UNAVAILABLE]: ErrorCategory.INTERNAL,
    [exports.ErrorCode.MAINTENANCE_MODE]: ErrorCategory.INTERNAL,
    [exports.ErrorCode.FEATURE_NOT_IMPLEMENTED]: ErrorCategory.INTERNAL,
    [exports.ErrorCode.CIRCUIT_BREAKER_OPEN]: ErrorCategory.EXTERNAL_SERVICE,
    [exports.ErrorCode.CIRCUIT_BREAKER_HALF_OPEN]: ErrorCategory.EXTERNAL_SERVICE,
};
var ErrorSeverity;
(function (ErrorSeverity) {
    ErrorSeverity["DEBUG"] = "debug";
    ErrorSeverity["INFO"] = "info";
    ErrorSeverity["WARNING"] = "warning";
    ErrorSeverity["ERROR"] = "error";
    ErrorSeverity["CRITICAL"] = "critical";
})(ErrorSeverity || (exports.ErrorSeverity = ErrorSeverity = {}));
exports.CategoryToSeverity = {
    [ErrorCategory.VALIDATION]: ErrorSeverity.INFO,
    [ErrorCategory.AUTHENTICATION]: ErrorSeverity.WARNING,
    [ErrorCategory.AUTHORIZATION]: ErrorSeverity.WARNING,
    [ErrorCategory.NOT_FOUND]: ErrorSeverity.INFO,
    [ErrorCategory.CONFLICT]: ErrorSeverity.WARNING,
    [ErrorCategory.RATE_LIMIT]: ErrorSeverity.WARNING,
    [ErrorCategory.BUSINESS_LOGIC]: ErrorSeverity.WARNING,
    [ErrorCategory.EXTERNAL_SERVICE]: ErrorSeverity.ERROR,
    [ErrorCategory.DATABASE]: ErrorSeverity.ERROR,
    [ErrorCategory.INTERNAL]: ErrorSeverity.CRITICAL,
};
exports.ErrorCodeToStatusCode = {
    [exports.ErrorCode.VALIDATION_ERROR]: 400,
    [exports.ErrorCode.INVALID_REQUEST]: 400,
    [exports.ErrorCode.INVALID_PARAMETER]: 400,
    [exports.ErrorCode.MISSING_REQUIRED_FIELD]: 400,
    [exports.ErrorCode.INVALID_FORMAT]: 400,
    [exports.ErrorCode.AUTHENTICATION_FAILED]: 401,
    [exports.ErrorCode.TOKEN_EXPIRED]: 401,
    [exports.ErrorCode.TOKEN_INVALID]: 401,
    [exports.ErrorCode.REFRESH_TOKEN_EXPIRED]: 401,
    [exports.ErrorCode.CREDENTIALS_INVALID]: 401,
    [exports.ErrorCode.ACCOUNT_LOCKED]: 401,
    [exports.ErrorCode.ACCOUNT_DISABLED]: 401,
    [exports.ErrorCode.MFA_REQUIRED]: 401,
    [exports.ErrorCode.MFA_INVALID]: 401,
    [exports.ErrorCode.PERMISSION_DENIED]: 403,
    [exports.ErrorCode.FORBIDDEN]: 403,
    [exports.ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
    [exports.ErrorCode.RESOURCE_ACCESS_DENIED]: 403,
    [exports.ErrorCode.NOT_FOUND]: 404,
    [exports.ErrorCode.USER_NOT_FOUND]: 404,
    [exports.ErrorCode.RESOURCE_NOT_FOUND]: 404,
    [exports.ErrorCode.ENDPOINT_NOT_FOUND]: 404,
    [exports.ErrorCode.CONFLICT]: 409,
    [exports.ErrorCode.DUPLICATE_ENTRY]: 409,
    [exports.ErrorCode.RESOURCE_ALREADY_EXISTS]: 409,
    [exports.ErrorCode.VERSION_CONFLICT]: 409,
    [exports.ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
    [exports.ErrorCode.QUOTA_EXCEEDED]: 429,
    [exports.ErrorCode.BUSINESS_RULE_VIOLATION]: 400,
    [exports.ErrorCode.INSUFFICIENT_BALANCE]: 400,
    [exports.ErrorCode.PLAN_LIMIT_REACHED]: 400,
    [exports.ErrorCode.OPERATION_NOT_ALLOWED]: 400,
    [exports.ErrorCode.WORKFLOW_ERROR]: 400,
    [exports.ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,
    [exports.ErrorCode.THIRD_PARTY_API_ERROR]: 502,
    [exports.ErrorCode.PAYMENT_GATEWAY_ERROR]: 502,
    [exports.ErrorCode.EMAIL_SERVICE_ERROR]: 502,
    [exports.ErrorCode.DATABASE_ERROR]: 500,
    [exports.ErrorCode.RECORD_NOT_FOUND]: 500,
    [exports.ErrorCode.UNIQUE_CONSTRAINT_VIOLATION]: 500,
    [exports.ErrorCode.FOREIGN_KEY_VIOLATION]: 500,
    [exports.ErrorCode.INTERNAL_ERROR]: 500,
    [exports.ErrorCode.SERVICE_UNAVAILABLE]: 503,
    [exports.ErrorCode.MAINTENANCE_MODE]: 503,
    [exports.ErrorCode.FEATURE_NOT_IMPLEMENTED]: 501,
    [exports.ErrorCode.CIRCUIT_BREAKER_OPEN]: 503,
    [exports.ErrorCode.CIRCUIT_BREAKER_HALF_OPEN]: 503,
};
exports.UserFriendlyMessages = {
    [exports.ErrorCode.AUTHENTICATION_FAILED]: "Invalid credentials. Please check your email and password.",
    [exports.ErrorCode.TOKEN_EXPIRED]: "Your session has expired. Please log in again.",
    [exports.ErrorCode.TOKEN_INVALID]: "Session invalid. Please log in again.",
    [exports.ErrorCode.REFRESH_TOKEN_EXPIRED]: "Your session has expired. Please log in again.",
    [exports.ErrorCode.CREDENTIALS_INVALID]: "Invalid email or password.",
    [exports.ErrorCode.ACCOUNT_LOCKED]: "Your account has been locked. Please contact support.",
    [exports.ErrorCode.ACCOUNT_DISABLED]: "Your account has been disabled. Please contact support.",
    [exports.ErrorCode.PERMISSION_DENIED]: "You don't have permission to perform this action.",
    [exports.ErrorCode.FORBIDDEN]: "Access denied.",
    [exports.ErrorCode.INSUFFICIENT_PERMISSIONS]: "You don't have the required permissions.",
    [exports.ErrorCode.NOT_FOUND]: "The requested resource was not found.",
    [exports.ErrorCode.USER_NOT_FOUND]: "User not found.",
    [exports.ErrorCode.RESOURCE_NOT_FOUND]: "The requested resource was not found.",
    [exports.ErrorCode.DUPLICATE_ENTRY]: "This item already exists.",
    [exports.ErrorCode.RESOURCE_ALREADY_EXISTS]: "This resource already exists.",
    [exports.ErrorCode.RATE_LIMIT_EXCEEDED]: "Too many requests. Please try again later.",
    [exports.ErrorCode.QUOTA_EXCEEDED]: "You have exceeded your quota.",
    [exports.ErrorCode.INSUFFICIENT_BALANCE]: "Insufficient balance for this operation.",
    [exports.ErrorCode.PLAN_LIMIT_REACHED]: "You have reached your plan limit.",
    [exports.ErrorCode.OPERATION_NOT_ALLOWED]: "This operation is not allowed.",
    [exports.ErrorCode.INTERNAL_ERROR]: "Something went wrong. Please try again later.",
    [exports.ErrorCode.SERVICE_UNAVAILABLE]: "Service temporarily unavailable. Please try again later.",
    [exports.ErrorCode.MAINTENANCE_MODE]: "System is under maintenance. Please try again later.",
};
function getUserFriendlyMessage(code) {
    return (exports.UserFriendlyMessages[code] ??
        "An unexpected error occurred. Please try again.");
}
//# sourceMappingURL=error-types.js.map